### ISSUE TITLE
Loading afs_test_pkg leaves a dirty git status

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/disco#32]
Loading the test package from the [afs test pkg repo](https://github.com/archesproject/afs-test-pkg/tree/main/pkg) leaves a dirty git status.

Should the files be committed? Or ignored? Or have they been copied to an inappropriate location?

```
python3 manage.py packages -o load_package -s /usr/local/afs-test-pkg/pkg
git status
```
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	disco/72cc4dcf-9500-418f-a42e-7d980937a9db_preview.pdf
	disco/72cc4dcf-9500-418f-a42e-7d980937a9db_thumbnail.png
	disco/example-template.docx
```

**Comment by chiatt** [comment]
When those files were added to the afs-test-pkg we didn't have a disco project. Since that's changed, I think we should probably go ahead and remove those files from afs-test-pkg and add them to disco. Perhaps we should put them in a directory called `disco/reporting` rather than directly under `disco`.  

This would mean an extra step when installing disco, so we should include instructions to load the report template in the readme. I think it's: `python manage.py load_template -s disco/72cc4dcf-9500-418f-a42e-7d980937a9db.yaml`
